### ISSUE TITLE
Compatibility Issue with Sinytra Connector, Forge, and AppleSkin

### ISSUE THREAD

**Issue by Lucas-Carrarini** [squeek502/AppleSkin#299] opened 2024-04-30 23:42 UTC
I'm experiencing a compatibility problem with the Sinytra Connector, Forge, and AppleSkin combination while running Spice of Fabric on Forge. It appears that AppleSkin isn't functioning properly in this setup. With the Forge version, I can access the main screen, but end up crashing when attempting to enter a world. Moreover, the Fabric version fails to load altogether.

While the mod itself works fine with Spice of Fabric, it only operates properly when the loader is Fabric. It would be beneficial to resolve this issue to enable the diminishing systems of Spice of Fabric in Forge with the Sinytra Connector, as AppleSkin currently causes crashes in both Forge and Fabric versions with the Forge loader.

**Comment by squeek502** [comment] 2024-05-01 00:44
Duplicate of https://github.com/squeek502/AppleSkin/issues/283

**Closed as not planned by squeek502** 2024-05-01 00:44 UTC
