### ISSUE TITLE
REI Mixin Crash (fabric)

### ISSUE THREAD

**Issue by lazynessmind** [squeek502/AppleSkin#139] opened 2021-08-14 11:11 UTC
### Bug

When loading minecraft, this mod is trying to mixin **me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl** and its failing.

**Mixin:** apple.mixins.json:REITooltipMixin

### Log:
[latest.log](https://github.com/squeek502/AppleSkin/files/6986358/latest.log)

### Versions:
REI Version: 6.0.268
AppleSkin Version: 1.17-2.1.1

**Comment by squeek502** [comment] 2021-08-14 21:42
Update your AppleSkin, this has been fixed (duplicate of #134).

**Closed as completed by squeek502** 2021-08-14 21:42 UTC
Labels: duplicate
