### ISSUE TITLE
Food tooltip is not working if NEI is installed

### ISSUE THREAD

**Issue by Dukat863** [squeek502/AppleSkin#6] opened 2017-01-03 21:19 UTC
When NEI is installed, food tooltip is not showing up when looking at the item inside the inventory.
It also doesn't work when NEI item panel and NEI recipe searcher are used, but works fine with those from JEI.

This was already reported to NEI bug tracker back in August and in December by two other guys, but there was no response.
I'm reporting it here hoping that the fix is possible from this end.

Versions:
Forge 12.18.3.2185
CodeChickenCore 2.4.0.100
CodeChickenLib 2.5.1.185
NotEnoughItems 2.1.3.182
JEI 3.14.2.401
AppleSkin 1.0.5

**Comment by squeek502** [comment] 2017-01-03 23:20
I haven't looked at the NEI code, but I would assume it's because NEI isn't providing the ItemStack when they do their tooltip rendering or has custom tooltip rendering code that bypasses the Forge event that AppleSkin relies on.

See https://github.com/mezz/JustEnoughItems/issues/388 and https://github.com/mezz/JustEnoughItems/commit/311c5386075c4c35b76021cbb3656b06c2ab47b1 for when JEI added support for the relevant Forge event.

**Comment by xSparky911x** [comment] 2017-01-07 07:28
I can confirm this bug :(

**Comment by squeek502** [comment] 2017-01-07 09:45
Unfortunately there's not much I can do. AppleSkin was only able to be split from AppleCore because of the event added by Forge (I used to have to use ASM to hook into NEI/JEI), so if NEI doesn't fire the Forge event with the necessary information, then AppleSkin won't be compatible with NEI.

Reported to the NEI issue tracker here: https://github.com/TheCBProject/NotEnoughItems/issues/65

**Comment by xSparky911x** [comment] 2017-01-07 21:01
SkyFactory 3 has JEI, NEI and AppleSkin installed and working fine together :(

**Comment by covers1624** [comment] 2017-01-08 08:48
This can be closed now, fixed in NEI.

**Closed as completed** 2017-01-08 09:49 UTC
