### ISSUE TITLE
1.20.5 Support

### ISSUE THREAD

**Issue by sky-is-winning** [squeek502/AppleSkin#295] opened 2024-04-24 12:01 UTC
The Fabric 1.20.3 version which worked on both 1.20.3 and 1.20.4 crashes on load in 1.20.5.

**Comment by SAGESSE-CN** [comment] 2024-04-24 12:13
Sure, because mojang made lot of technical changes in 1.20.5.

**Comment by SAGESSE-CN** [comment] 2024-04-24 16:48
the neoforge development environment encountered some problems.

**Comment by squeek502** [comment] 2024-04-24 21:21
Just want to note that for Fabric, the 1.20.5 branch should be based on https://github.com/squeek502/AppleSkin/tree/24w14potato-fabric

**Comment by squeek502** [comment] 2024-04-24 21:31
Created new branches for 1.20.5, no updates made yet though:

- https://github.com/squeek502/AppleSkin/tree/1.20.5-neoforge
- https://github.com/squeek502/AppleSkin/tree/1.20.5-fabric

They are separate from the 1.20.x branch since it seems possible that we'll want to maintain 1.20.1, 1.20.4, and 1.20.5 versions separately.

**Comment by squeek502** [comment] 2024-04-24 23:05
Doing a bit of work on this, I think this might end up warranting bumping the version to `3.0.0`, since `FoodComponent` should probably change how the API works (I'm thinking we should delete `FoodValues` and use `FoodComponent` instead).

**Comment by squeek502** [comment] 2024-04-25 00:06
Committed my Fabric port here: https://github.com/squeek502/AppleSkin/commit/15b9ff0f76e24698aa35af6ae0412b65986705e1

Need to test the API changes still. I'm also unable to get a Neoforge environment working, so that might need to wait.

**Comment by SAGESSE-CN** [comment] 2024-04-25 00:15
~forge~ neoforge the gui layer is changed, i needs reimplements it with new api.

https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/client/event/RegisterGuiLayersEvent.java

**Comment by squeek502** [comment] 2024-04-25 00:20
By the way, I'm not planning on supporting Forge anymore, so we only need to update for Neoforge.

**Comment by SAGESSE-CN** [comment] 2024-04-25 00:53
the changes is caused by the vanilla, I'm not sure the fabric needs also?

**Comment by squeek502** [comment] 2024-04-25 01:24
It looks like Neoforge adds a lot of new layers that Vanilla doesn't have:
https://github.com/neoforged/NeoForge/blob/916bfcbc540abf1a1b1ba4162905a28aa754894d/patches/net/minecraft/client/gui/Gui.java.patch

So I don't think a change is needed for Fabric. However, the Fabric mixin can probably be simplified, since now there's a `renderFood` method in `InGameHud` that we can inject into instead.

EDIT: Made the simplification in the Fabric branch: https://github.com/squeek502/AppleSkin/commit/a7830bb814d19735e125d518beb0387de6f9ffe3

**Comment by squeek502** [comment] 2024-04-26 08:22
Released as v3.0.0

https://www.curseforge.com/minecraft/mc-mods/appleskin
https://modrinth.com/mod/appleskin
https://github.com/squeek502/AppleSkin/releases/tag/v3.0.0

**Closed as completed by squeek502** 2024-04-26 08:22 UTC
