### ISSUE TITLE
Vanilla Tweaks (and maybe others) custom food outlines?

### ISSUE THREAD

**Issue by Random-Penguin** [squeek502/AppleSkin#321] opened 2024-08-18 00:06 UTC
This may be a long shot, but since Vanilla Tweaks have started doing custom food textures in the hunger bar, maybe it could be possible to add custom outlines for these mini foods? Otherwise it conflicts with the hunger bar, but if it won't be possible, you could still make your own textures for the mod, with Pixelorama or something similar. It's what I did, amyways.

Edit: I don't know how to add labels, but in my opinion it would be an enhancement.

**Comment by squeek502** [comment] 2024-08-18 05:15
Resource packs can include a custom [assets/appleskin/textures/icons.png](https://github.com/squeek502/AppleSkin/blob/1.16-forge/resources/assets/appleskin/textures/icons.png) (or you can make a resource pack with custom AppleSkin textures to match the resource pack you're using)

If you're talking about something else, then you'll need to clarify.

**Comment by squeek502** [comment] 2024-08-18 07:40
Going to assume this is a duplicate of https://github.com/squeek502/AppleSkin/issues/319

**Closed as completed by squeek502** 2024-08-18 07:40 UTC
Labels: need more info
