### ISSUE TITLE
[Fabric 1.18.1] Transparent food icons in texture pack turns fully black 

### ISSUE THREAD

**Issue by GaleWings** [squeek502/AppleSkin#182] opened 2022-03-23 03:37 UTC
Normally it shows like this.
![1](https://user-images.githubusercontent.com/62740827/159618821-585edae7-5db2-4fa5-ab60-2d0bc9a024a6.png)

And it turns black with appleskin.
![2](https://user-images.githubusercontent.com/62740827/159618835-fa3d1bd0-189d-4dc4-803d-8e92e1a6e88f.png)

**Comment by SAGESSE-CN** [comment] 2022-03-30 02:24
I like this style :p

**Comment by SAGESSE-CN** [comment] 2022-03-30 02:55
![image](https://user-images.githubusercontent.com/6903353/160741842-fb62d8f7-b752-4613-9012-f61a630ea111.png)
Everything is all right

**Comment by Zentheon** [comment] 2022-06-24 01:35
I'm also working on a texturepack that uses transparency and it'd be great if it was fixed for Appleskin

**Comment by SAGESSE-CN** [comment] 2022-06-24 11:46
> I'm also working on a texturepack that uses transparency and it'd be great if it was fixed for Appleskin

i can’t reporduce this

**Comment by Zentheon** [comment] 2022-06-24 16:45
> > I'm also working on a texturepack that uses transparency and it'd be great if it was fixed for Appleskin
> 
> i can’t reporduce this

Huh? I mean, it's pretty clear (Or not, since that's what the issue is about). Here's a pack as an example
[test.zip](https://github.com/squeek502/AppleSkin/files/8978155/test.zip)
I'm on fabric too so I don't know if forge has the same problem. With appleskin installed empty hearts will be transparent but not the food bars like vanilla does

**Comment by SAGESSE-CN** [comment] 2022-06-28 10:26
In forge:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/176147541-5e47fd9a-38c8-4f73-8d5d-25413ec210ab.png">

In fabric:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/6903353/176156973-4359c6a9-0b81-4c95-9b28-e76214c3aa4f.png">

**Comment by GirafiStudios** [comment] 2022-07-17 23:15
Wasn´t this fixed by https://github.com/squeek502/AppleSkin/pull/189? :)

**Comment by squeek502** [comment] 2022-07-17 23:30
Yes, but I haven't released new versions with the fix included. Will wait to close until that happens.

**Comment by squeek502** [comment] 2022-08-10 07:34
Should be fixed in `fabric-mc1.18.2-2.4.1` and `fabric-mc1.19-2.4.1`

**Closed as completed by squeek502** 2022-08-10 07:34 UTC
Labels: bug
