### ISSUE TITLE
Outdated Fabric API causes problems

### ISSUE THREAD

**Issue by Boobies** [squeek502/AppleSkin#54] opened 2019-10-24 21:50 UTC
You seem to be embedding the Fabric API and the version you are using causes the game to display the update aquatic screen in the main menu for 1.14 instead of the village and pillage one. All mods that do this cause this problem.

**Comment by Boobies** [comment] 2019-10-24 21:52
You seem to be embedding the Fabric API and the version you are using causes the game to display the update aquatic screen in the main menu for 1.14 instead of the village and pillage one. All mods that do this cause this problem.

**Comment by squeek502** [comment] 2019-10-24 21:55
Thanks for the heads up, will recompile with latest when I get a chance.

**Comment by squeek502** [comment] 2019-10-24 21:59
Do you happen to know if its embedding the API that causes it or just the outdated embedded version that causes it (i.e. would updating the embedded version fix it)?

**Comment by Boobies** [comment] 2019-10-25 07:57
Updating it will fix it. You probably shouldn't be embedding it in the first place but if it works for you, oh well. :)

**Comment by squeek502** [comment] 2019-10-25 08:12
Hm, I thought nested jars was supposed to handle this particular scenario correctly (i.e. load the latest Fabric API found, not necessarily the nested version). Haven't been keeping up with Fabric so I'm not sure what the best practice is.

Out of curiosity, have you tested that when *only* AppleSkin and Fabric API (some version that doesn't have this bug) are installed it still happens? Maybe some other mod is causing Fabric to choose an outdated version of Fabric API due to some dependency version a different mod is setting.

**Comment by squeek502** [comment] 2019-10-25 08:22
Confirmed that this is fixed when using only AppleSkin and latest Fabric API. My guess is that some other mod is (maybe accidentally) telling Fabric that it needs an older version of Fabric API; AppleSkin itself doesn't care which version is loaded and nested jars seem to be behaving properly here.

Will probably still release a new version so that this is fixed when using AppleSkin on its own, so I'll keep this open until I do that.

**Comment by squeek502** [comment] 2019-11-25 02:47
Fixed by https://github.com/squeek502/AppleSkin/commit/f7deefcaa9ac791bdcd7f589cea629e093563b6f

**Closed as completed by squeek502** 2019-11-25 02:47 UTC
Labels: fabric
