### ISSUE TITLE
org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517) ~[mixin-0.8.5.jar%2314!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} -- MOD appleskin --

### ISSUE THREAD

**Issue by njasak** [squeek502/AppleSkin#207] opened 2022-08-28 11:33 UTC
Keeps crashing, would you know maybe why? 
[crash-2022-08-28_07.12.42-fml.txt](https://github.com/squeek502/AppleSkin/files/9439550/crash-2022-08-28_07.12.42-fml.txt)

**Comment by SAGESSE-CN** [comment] 2022-08-28 11:40
Duplicate of #202

**Comment by njasak** [comment] 2022-08-28 11:41
I'll try that sir thanks.

**Closed as completed** 2022-08-28 11:41 UTC
Labels: duplicate
