### ISSUE TITLE
Error on version above forge 41.0.33 (1.19)

### ISSUE THREAD

**Issue by Joshernoob** [squeek502/AppleSkin#193] opened 2022-07-11 16:49 UTC
Mod Version: appleskin-forge-mc1.19-2.4.0

Tested Forge Versions: 41.0.34, 41.0.45- 41.0.91 (skipped a few as most of mods needed .45 or higher)

PIcture of crash:
![Screenshot 2022-07-11 124146](https://user-images.githubusercontent.com/64944433/178315878-19a8d123-0c7b-485f-902f-bd3435fe6d87.png)

Log of crash : 
[latest.log](https://github.com/squeek502/AppleSkin/files/9086052/latest.log)

Crash report: 
[crash-2022-07-11_12.41.28-fml.txt](https://github.com/squeek502/AppleSkin/files/9086062/crash-2022-07-11_12.41.28-fml.txt)

**Comment by GirafiStudios** [comment] 2022-07-11 18:24
Duplicate of https://github.com/squeek502/AppleSkin/issues/192

**Closed as completed by GirafiStudios** 2022-07-11 18:24 UTC
