### ISSUE TITLE
Incompatible with Item Borders

### ISSUE THREAD

**Issue by Sunconure11** [squeek502/AppleSkin#276] opened 2023-11-17 21:38 UTC
https://github.com/AHilyard/ItemBorders/issues/22

Scrolling through the food tab causes this crash.

**Comment by squeek502** [comment] 2023-11-17 21:53
Looks like something that would be fixed by https://github.com/squeek502/AppleSkin/pull/235. However, I didn't realize that 1.19.2 is still the most popular 1.19.x release, so the fix has only been released for Minecraft 1.19.4.

Still undecided if I'll release a new 1.19.2 version.

**Comment by squeek502** [comment] 2023-11-17 22:01
Note also that this may actually be unrelated to Item Borders--it may be some other mod adding an item that claims it's a food via `isFood()` but returns null from `getFoodComponent()`

EDIT: You could try using the version in https://github.com/squeek502/AppleSkin/pull/235#issuecomment-1535439942 to track down the item causing it.

**Comment by Sunconure11** [comment] 2023-11-17 22:26
I will have to wait on another mod to fix an unrelated issue, before I can try that.

I do see a user mentioning Spice of Fabric in that comment chain, and I do have that installed.

**Comment by Sunconure11** [comment] 2023-11-21 12:19
Going to test now.

**Comment by Sunconure11** [comment] 2023-11-21 12:29
[crash-2023-11-21_07.27.41-client.txt](https://github.com/squeek502/AppleSkin/files/13426212/crash-2023-11-21_07.27.41-client.txt)

[latest.log](https://github.com/squeek502/AppleSkin/files/13426214/latest.log)

**Comment by Sunconure11** [comment] 2023-11-21 12:31
We need it to dump the mod the item is from. This will help in finding the error's cause.

**Comment by squeek502** [comment] 2023-11-21 13:12
I can't reproduce this with the following mods and Quilt Loader 0.21.2:

```
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.5.85-fabric.jar
brewinandchewin-fabric-2.3.1+1.19.2.jar
farmers-delight-fabric-mc1.19-1.19.2-1.3.10.1.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
Iceberg-1.19.1-fabric-1.0.46.jar
ItemBorders-1.19-fabric-1.1.6.jar
letsdo-api-fabric-1.1.0.jar
letsdo-candlelight-fabric-1.1.9.jar
qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2.jar
```

Both `pizza_slice` item tooltips work for me:

![1](https://github.com/squeek502/AppleSkin/assets/2389051/d04d3e1f-5a58-4967-b005-195a70e4aac1)

![2](https://github.com/squeek502/AppleSkin/assets/2389051/9b357b5f-3b46-4639-b765-c7aba97cf623)

**Comment by squeek502** [comment] 2023-12-13 06:58
Ended up releasing a new version for 1.19.2 with the fix from https://github.com/squeek502/AppleSkin/pull/235 included, so this incompatibility should be fixed if you update to that.

**Closed as completed by squeek502** 2023-12-13 06:58 UTC
Labels: bug, mod compat, fabric
