### ISSUE TITLE
Freeze when hovering over rotten flesh. 

### ISSUE THREAD

**Issue by Darkere** [squeek502/AppleSkin#153] opened 2021-10-27 16:54 UTC
Had a user complain that his game was freezing when selecting rotten flesh on his hotbar. 

Using Visual VM we finally figured out that the game was stuck  in AppleSkin.
![image](https://user-images.githubusercontent.com/4283717/139110815-f46d79a0-b54c-4738-942b-bb044059fd70.png)

Snapshot file: 
[snapshot.zip](https://github.com/squeek502/AppleSkin/files/7427952/snapshot.zip)
 

Appleskin 1.16x-2.1.0
Forge-36.2.4
Enimgatica 6 0.5.16

**Comment by SAGESSE-CN** [comment] 2021-10-27 17:55
Thank you for your feedback, I'm not very familiar with Visual VM, is that a call to 85ms?

**Comment by Darkere** [comment] 2021-10-27 18:10
That is a call that ran for 85413 milliseconds or 85 seconds.

**Comment by SAGESSE-CN** [comment] 2021-10-27 18:27
That looks like "85.413" not "85,413".

But that's not normal, it should end after 4/5 count loops, do you know the specific value of the current player food level/saturation level/exhaustion level?

**Comment by Darkere** [comment] 2021-10-27 18:34
It is probably visible from this screenshot https://cdn.discordapp.com/attachments/544589452492931076/902939187840434207/unknown.png


You can see on the last line that VisualVm uses "," for the decimal separator and "." for thousands. A quick test confirms this.

**Comment by SAGESSE-CN** [comment] 2021-10-28 04:34
I'm sorry, but I can't reproduce the problem.

Without other mods + new single player world + hold rotten flesh in main hand:
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/6903353/139186275-2b2c3252-1e53-4f8f-81ef-ae65eb42bb8d.png">

With Enimgatica 6 0.5.16 + new single player world + hold rotten flesh in main hand:
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/6903353/139186225-5b5bbb1d-821e-4582-a376-7a80cb57147a.png">

**Comment by SAGESSE-CN** [comment] 2021-10-28 10:36
I had a discussion of this user on discord, he said the problem disappeared after AppleSkin was reinstalled.

**Comment by squeek502** [comment] 2021-10-28 21:54
Strange, not sure how this could happen. Doesn't seem like there's any potential for an infinite loop in the current implementation unless I'm missing something.

**Comment by Darkere** [comment] 2021-10-28 22:20
From a quick glance. Foodlevel 19 and saturation level 0 could loop infinitely

**Comment by squeek502** [comment] 2021-10-28 22:44
Don't think so, since `exhaustionLevel` is increased each iteration, and `exhaustionLevel` is used to decrease `foodLevel` whenever it is over a certain threshold.

Could definitely be worth trying to throw some sort of property testing/fuzz testing at it though to ensure that it doesn't hang on any inputs.

**Comment by SAGESSE-CN** [comment] 2021-10-29 03:01
I do some tests to confirm that an infinite loop would occur if `saturationLevel` or `exhaustionLevel` is infinite or nan.

**Comment by squeek502** [comment] 2021-11-02 06:17
Might be fixed in 2.2.0 via #155. Closing for now, please re-open if this occurs again.

**Closed as completed by squeek502** 2021-11-02 06:17 UTC
Labels: bug, can't reproduce
