### ISSUE TITLE
[1.13.2] Getting disconnected

### ISSUE THREAD

**Issue by chaos234** [squeek502/AppleSkin#31] opened 2019-04-03 22:38 UTC
I use on my server and on my client the same AppleSkin Versions but getting kicked from the server: https://i.imgur.com/f0o5WfL.png

Why is there such check and can I disable it because such checks are sucking hard. I understand them only, if the mod changes the gameplay but this mod doesn't do it so please remove this check or implement an option to disable it, because it isn't needed, thanks.

**Comment by squeek502** [comment] 2019-04-03 23:17
Not sure, will look into it when I get a chance. What Forge version are you using?

(note to myself) Relevant code: https://github.com/squeek502/AppleSkin/blob/1.13.2/java/squeek/appleskin/network/SyncHandler.java#L24-L26

**Comment by chaos234** [comment] 2019-04-04 02:04
Forge: 1.13.2-25.0.107

**Comment by TheLimePixel** [comment] 2019-04-06 21:10
I was about to report it, but I see it already is reported. However, I don't see the actual error because of which the player gets kicked in your image, so here it is https://pastebin.com/R1GCyAtd

**Comment by squeek502** [comment] 2019-04-06 21:29
> I was about to report it, but I see it already is reported. However, I don't see the actual error because of which the player gets kicked in your image, so here it is https://pastebin.com/R1GCyAtd

Is there more of the error below that? If so, could you post that too?

**Comment by squeek502** [comment] 2019-04-07 05:02
Please try v1.0.10: https://minecraft.curseforge.com/projects/appleskin/files/2696337

**Comment by TheLimePixel** [comment] 2019-04-07 16:36
Yeah, that change caused #32

**Comment by squeek502** [comment] 2019-04-07 20:16
> Yeah, that change caused #32

#32 is a separate problem caused by a change in Forge.

**Comment by TheLimePixel** [comment] 2019-04-07 21:08
:man_facepalming: I forgot I updated forge... derp

**Comment by squeek502** [comment] 2019-04-08 22:52
Closing assuming this is fixed. @chaos234 please re-open if v1.0.10 didn't fix it for you.

**Closed as completed by squeek502** 2019-04-08 22:52 UTC
Labels: bug
