### ISSUE TITLE
Resource pack not working in 1.21

### ISSUE THREAD

**Issue by Enderjay280** [squeek502/AppleSkin#315] opened 2024-07-21 16:20 UTC
Hi, I've made a quick resource pack that replaces the hunger bar icons with cooked beef icons. I replaced the /assets/minecraft/textures/gui/sprites/hud/ icons as well as the /assets/appleskin/textures/icons.png.
I tested it out and the appleskin icons don't work on my pc. I can't post any pictures right now but here's the resource pack. 
[beef_hud.zip](https://github.com/user-attachments/files/16325261/beef_hud.zip)

**Comment by squeek502** [comment] 2024-07-21 22:58
Can't reproduce, seems to work fine for me.

NeoForge:

![2024-07-21_15 56 14](https://github.com/user-attachments/assets/962a063a-b9cd-4e2f-9f16-72a0e4d9cb00)

Fabric:

![2024-07-21_15 57 26](https://github.com/user-attachments/assets/8fa9f605-19c2-435d-a947-7bed677d1600)

**Comment by Enderjay280** [comment] 2024-07-21 23:28
Thanks for checking! Maybe it could be an other mod interfering? I'll have to check my mod list when I get home.

**Comment by Enderjay280** [comment] 2024-07-22 20:48
Does the resource pack need to be a .zip for it to work? I remember testing it with the resourcepack unzipped and it the overlays didn't work.

**Comment by squeek502** [comment] 2024-07-25 05:49
Not sure, but there shouldn't be anything unique about AppleSkin with regards to resource packs, so I'm going to close this.

**Closed as completed by squeek502** 2024-07-25 05:49 UTC
Labels: can't reproduce
